version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    #command: npm start
    command: sh -c "echo 'Waiting for user input...' && sleep infinity"
  
  doc2json:
    build: ./utils/doc2json/
    volumes:
      - ./utils/doc2json:/app
      - ./crosswords:/crosswords
      - ./tmp/docs:/docs
    

volumes:
  node_modules:

# docker-compose exec app sh
# docker-compose up -d 
# docker-compose up -d --build
# docker-compose run --rm doc2json